name: hds-events-tm

services:
  api:
    build:
      context: api
    image: hdstmevents/api:latest
    restart: unless-stopped
    environment:
      DATABASE_CONNSTR: postgres://hdstmevents:Passw0rd!@localhost:5432/hdstmevents?pool_max_conns=10
      ADMIN_KEY: developer-test-key
    ports:
      - 8081:8081
    networks:
      - server-network
  app:
    build:
      context: app
    image: hdstmevents/app:latest
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - server-network
  ingress:
    image: nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-network
  db:
    image: postgres:16
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: Passw0rd!
      POSTGRES_USER: hdstmevents
    networks:
      - server-network
    ports:
      - 5432:5432

networks:
  server-network:
    driver: bridge
