name: hds-events-tm

services:
  api:
    build:
      context: api
    image: hdstmevents/api:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    networks:
      - server-network
  app:
    build:
      context: app
    image: hdstmevents/app:latest
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - server-network
  ingress:
    image: nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server-network    

networks:
  server-network:
    driver: bridge
