name: hds-events-tm

services:
  app:
    build:
      context: app
    image: hdstmevents/app:latest
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - server-network

networks:
  server-network:
    driver: bridge
