name: CI
on:
  push:
    branches:
      - main
  pull_request:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: yarn
      - run: yarn lint
      - run: yarn test
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: app
          push: ${{ env.BRANCH_NAME == 'main' }}
          tags: hdstmevents/app:latest